# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180328_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d/', verbose_name='标题配图'),
        ),
    ]
